### PR TITLE
Link DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates the code that generates new DOI links.

Cheers!

### CODE REVIEW

**Comment by katrinleinweber** [comment]
`[…] `[`Running R installer`](https://ci.appveyor.com/project/jeremyrcoyle/sl3-e9tm0/build/1.0.3#L15) results in: ´This command cannot be run due to the error: The file or directory is corrupted and unreadable.´ which I presume is not due to my change.

**Comment by nhejazi** [comment]
Hello @katrinleinweber, thanks for your contribution! We'll take a look and try to get it merged soon. In regards to the error that you're seeing, as best as I can tell, that appears to be specific to the builds that are happening on `appveyor`, and I've been seeing it for other packages over the last few days (e.g., [`hal9001`](https://ci.appveyor.com/project/jeremyrcoyle/hal9001/build/1.0.44)) so I don't think the issue is specific to `sl3`.

**Comment by nhejazi** [comment]
I've now confirmed the build issue is specific to `appveyor` so this will be merged. Thanks again for the contribution.

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
