### PR TITLE
Documentation Improvements

### LINKED ISSUE #23: Document Learners
Currently using `@rdname undocumented_learner` for a number of learners that I haven't had a chance to document yet

### PR DESCRIPTION
**Pull request by nhejazi**
This PR is intended to substantially improve the documentation provided for using the many learners that are made accessible through `sl3`. When ready, this PR will resolve #23, at least in part.

### CODE REVIEW

**Comment by nhejazi** [comment]
Learners documented __as of 197ff48__:

- [x] `Lrnr_h2o_glm`
- [x] `Lrnr_h2o_grid`
- [x] `Lrnr_h2o_classifier`
- [x] `Lrnr_h2o_mutator`
- [x] `Lrnr_mean`
- [x] `Lrnr_nnls`
- [x] `Lrnr_pkg_SuperLearner`
- [x] `Lrnr_pkg_SuperLearner_screener`
- [x] `Lrnr_randomForest`
- [ ] `Lrnr_sl`
- [x] `Lrnr_solnp_density`
- [x] `Lrnr_subset_covariates`
- [x] `Lrnr_xgboost`

**Review by jeremyrcoyle — COMMENTED** [review]
Thanks for all your hard work on this. Why did so many packages have to move from `Suggests` to `Depends`?

**Comment by nhejazi** [comment]
Happy to help. That particular requirement seems to arise from using `@importFrom` tags. After adding these to make the function calls explicit, `devtools::check` throws an error (`Namespace dependency not required:` package name) about a package being listed in the `NAMESPACE` dependencies but not being in the `Depends` of `DESCRIPTION`. I didn't look for a way around this, but there might be a way to keep them in `Suggests`. Feel free to let me know if you'd like revisions prior to merging.

**Comment by jeremyrcoyle** [comment]
Let's just not tag them as imports. Thats what both `mlr` and `SuperLearner` do for their learners to keep the number of dependencies low.

**Comment by osofr** [comment]
Thanks for the hard work!

I think we shouldn't be using `importFrom()` unless it is absolutely necessary. Why can't we use, e.g.,  `h2o::h2o.getGrid` and hence avoid `importFrom(h2o, h2o.getGrid)`.

Also, we don't need to be doing `importFrom()` for any `data.table` functions, we are already importing the entire namespace of the data.table package, so all data.table functions are already available.

**Comment by jeremyrcoyle** [comment]
Regarding `data.table`, maybe we should try to clean that up and only import the functions that we're using. Unless we need to be importing the entire namespace? (Says the person who probably imported the entire namespace).

**Comment by osofr** [comment]
We have to import entire `data.table` namespace, otherwise we start getting really weird evaluation errors. Tried that before, doesn't work, probably because of unique data.table syntax `dt[, :=]`

**Comment by nhejazi** [comment]
I believe all of the above concerns have been resolved as of f232bd7 re: increases in `Depends` and use of `@importFrom` tags. I'll leave this open for now so as to facilitate further discussion on this PR. Since all CI builds pass, I will merge the PR at 2pm PDT if there are no further comments by then.

**Pull request merged**
