### PR TITLE
fixes to Lrnr_stratified

### PR DESCRIPTION
**Pull request by jeremyrcoyle**
* task$subset now drops folds, allowing internal learner to be cv (otherwise it was trying to index on the subset data with full data folds)
* predict now only generated predictions for strata in prediction task (this was generating errors if a strata was present in training but not prediction)
* the resorting code for predict now works for both vectors and matricies

### CODE REVIEW

**Comment by wilsoncai1992** [comment]
I haven't been using this Lrnr lately. Is this related to density sl3?

**Comment by jeremyrcoyle** [comment]
A colleague is using it in an optimal treatment context to ensure that they can pick up a differential treatment effect. I just wanted to make sure you saw it since you're the original user. I'll go ahead and merge.

**Comment by wilsoncai1992** [comment]
Sounds good!

**Comment by wilsoncai1992** [comment]
Thank you Jeremy!

**Pull request merged**
