### PR TITLE
implement Lrnr_stratified

### PR DESCRIPTION
**Pull request by wilsoncai1992**
A simple test is included. 

As a side note, when I `make md` it throws error:
```
pandoc: Could not fetch https://img.shields.io/codecov/c/github/tlverse/sl3/master.svg
TlsExceptionHostPort (HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,HandshakeFailure)])")) "img.shields.io" 443
Error: pandoc document conversion failed with error 67
```

### CODE REVIEW

**Comment by nhejazi** [comment]
The link to the coverage badge (https://img.shields.io/codecov/c/github/tlverse/sl3/master.svg) appears to be working for me. It's possible this was down at some point in time (?) or that you didn't have a working internet connection when you ran `make md`.

**Comment by wilsoncai1992** [comment]
Pasting that into browser works for me as well. Maybe it is some local
config, but I don't expect it happen to a fresh install R on my laptop

**Comment by jeremyrcoyle** [comment]
Can you pull changes from master? That should fix the appveyor error you're currently getting.

**Comment by wilsoncai1992** [comment]
on it

**Comment by wilsoncai1992** [comment]
just merged from master

**Comment by wilsoncai1992** [comment]
API rate limit error in appveyor. It is beyond my understanding of the build system

**Comment by wilsoncai1992** [comment]
h2o fail in travis.

**Comment by wilsoncai1992** [comment]
Back to the pandoc thread: here is my pandoc version:

```
╰─➤  pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/wilsoncai/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jeremyrcoyle** [comment]
Check always generates some garbage about h2o, even when it passes. The failing tests are listed here: https://travis-ci.org/tlverse/sl3/jobs/441766624#L2444 . These aren't related to your changes. Can you verify that your PR passes locally?

**Comment by wilsoncai1992** [comment]
Yes it does pass locally. We can extend the unit test to be more granular
later.

**Review by jeremyrcoyle — APPROVED** [review]

**Comment by jeremyrcoyle** [comment]
Ok, then let's merge this

**Review by nhejazi — APPROVED** [review]
Let's go ahead and merge. We can fix any remaining problems afterward.

**Pull request merged**
