### PR TITLE
All learners accept formula

### PR DESCRIPTION
**Pull request by rachaelvp**
- User can supply model formula to Lrnr_glm, so long as the `formula`'s regressor variables correspond to column names in `task$X` and the response variable matches `task$nodes$outcome`.
- Added tests for the formula.
- Fixed a typo in `Lrnr_gam` that called "stas" instead of "stats" package.
- Stopped the skipping of a `Lrnr_glmnet` test.

### CODE REVIEW

**Comment by nhejazi** [comment]
Looks good all around, except that the change to `Lrnr_glm` causes something in the SL test to fail https://ci.appveyor.com/project/tlverse/sl3/builds/39343652#L6250 wrt kept covariates.

**Comment by jeremyrcoyle** [comment]
sl3 learners don't accept formulas by design, as the model matrix code in R is pretty inefficient. Users should use the covariates param, and Lrnr_define_interactions for interaction terms to replicate the formula functionality in a learner independent and efficient way.

**Comment by rachaelvp** [comment]
I added this functionality based on a discussion with a user yesterday who asked, “quick q: can I specify the form of a glm in sl3 the way I can write a quick wrapper fun for regular super learner?” When I asked how the desired formula would differ from the default main terms GLM, they responded with “say you wanted a really basic SL that compared several diff glm, one with square or cubic terms, and then diff subsets of the covariates.”

You’re right that users *should* go about this in a more efficient manner, but what if they would rather use formula and don’t care about efficiency? What if the user won’t use sl3 otherwise? In some edge cases, the covariates param and Lrnr_define_interactions cannot replicate a formula (e.g., “Y ~ X1:X2”).  

In Lrnr_glm docs, I provide an example with Lrnr_define_interactions. I can include another example with covariates param. Even with this mini tutorial on how to use the efficient workaround, I still thought it would be helpful to the user to provide them with the formula option. This is just a suggestion. We can cancel the PR if you think it’s better to not provide this option.

**Comment by nhejazi** [comment]
My $0.02 is that this comes down to an issue of efficiency v usability. While the design and defaults of `sl3` should generally lean in favor of efficiency, this can lead to an _avoidable_ loss in usability if we lean in too far. Basically anyone who's ever learned R is familiar with the formula syntax of `glm()` (and it's widely adopted, e.g., across `gam()`, etc), so it would really make things easier for users to be able to leverage that familiarity/knowledge, even if it leads to some computational efficiency. As long as we note the more efficient approach in the documentation and embrace that it the defaults, then most users, many of whom are probably just running slightly modified versions of example code, will still end up following the more efficient paradigm.

I think it's beneficial to support formulae both to leverage existing user familiarity and so that edge cases like that described above can be handled.

**Comment by jeremyrcoyle** [comment]
Thanks for doing this!

**Pull request merged**
