### PR TITLE
Neural Net Arsenal

### PR DESCRIPTION
**Pull request by imalenica**
How is this a modern implementation without a bunch of NNs?

-Adding LSTM and bidirectional LSTMs. More to come.

### CODE REVIEW

**Comment by osofr** [comment]
Fantastic! Is this only applicable to time series or has wider applicability?

**Comment by imalenica** [comment]
I was a bit biased with what I started with... These 2 are recurrent type NNs, so any data that has some ordered structure should be applicable (time series, natural language processing, etc).

**Comment by osofr** [comment]
Very nice. Any particular reason for going with `kerasR` package vs. `keras` from Rstudio?

**Comment by imalenica** [comment]
I was just more familiar with kerasR syntax, and for these two it did not seem to make a lot of difference. kerasR doesn't seem to support all the functionality of keras (mostly related to preprocessing), so for other NNs I'll probably rely more on the rstudio package.

**Pull request merged**
