### PR TITLE
auto-deploy drat

### LINKED ISSUE #26: set up drat repo via github http
Setting up drat repo with an automatically compiled dev version of the package is becoming more popular (as an alternative to `install_github`). 

The package tar is added to drat repo only if all the checks have passed, thus eliminating the possibility of someone installing the development version that is in the error state.

Basic description: https://github.com/eddelbuettel/drat
Working example: https://github.com/dmlc/drat

### PR DESCRIPTION
**Pull request by nhejazi**
This PR is intended to add support for automatically updating a `drat` repository, hosted under the branch `gh-pages`. When ready, this PR will resolve #26.

### CODE REVIEW

**Comment by nhejazi** [comment]
Note that this PR is now mature and ready to be checked/merged. Please ignore the glaring build failure as this only applies to the _old release of R_. Builds on the current distribution and development release of R are passing on both Travis and Appveyor.

**Review by jeremyrcoyle — COMMENTED** [review]
lgtm!

**Comment by nhejazi** [comment]
@osofr -- just checking in to make sure this covers the idea for a `drat` repo that you brought up in #26 -- does this seems sufficient? Thanks again for the review!

**Review by osofr — APPROVED** [review]
Fantastic! Thanks for doing that.

**Pull request merged**
