### PR TITLE
Travis run skips keras test

### PR DESCRIPTION
**Pull request by rachaelvp**
does travis run keras test or skip it?

### CODE REVIEW

**Comment by nhejazi** [comment]
Looks like Travis skips the test: https://travis-ci.com/github/tlverse/sl3/jobs/489572853#L1535

**Comment by rachaelvp** [comment]
@podTockom, the Keras test is not running on Travis. Do you mind taking a look at this?

**Comment by imalenica** [comment]
Yes, I remember we made it skip due to various python issues via Travis, in particular kerasR.

**Comment by nhejazi** [comment]
Should we try to fix this or just ignore? I think Tensorflow, keras, etc., should all be correctly installed/configured on the Travis build

**Comment by imalenica** [comment]
Could look into it again, I forgot what the problem was at this point.

**Comment by nhejazi** [comment]
I guess the question comes down to how much we expect the Keras functionality to be used. If supporting it seems worthwhile, then we should try to make sure it at least gets tested on Linux builds (Travis). Currently, the line
```r
reticulate::py_module_available("keras.models")
```
evaluates to `FALSE` on Travis (and, certainly, it does on Appveyor too), so the tests never get run. We got the Python dependencies properly installed (https://github.com/tlverse/sl3/blob/master/.travis.yml#L34) (and that took a while), so it should be a problem having to do with `reticulate` and not the Python installation itself.

**Pull request closed without merging**
