### PR TITLE
More TS Learners 

### PR DESCRIPTION
**Pull request by imalenica**
- Few edits to ARIMA to create same output as glm
- new learners: various GARCH models and ARFIMA

### CODE REVIEW

**Comment by jeremyrcoyle** [comment]
Rerunning the tests because it looks like a Travis issue, not an issue with the PR. If it turns out it fails again, you can always just push more commits and they'll be integrated into the PR.

**Comment by imalenica** [comment]
Yes- I closed it since Travis keeps throwing errors with test_zzz4_densitySL, and I can't figure out how is that connected to my PR.

**Comment by nhejazi** [comment]
Thanks for the note. It appears that it might still be an issue related to Travis, since the latest build (as of ea7d4a4) report fails with
```
0.38schecking whether package ‘sl3’ can be installed ... WARNING
Found the following significant warnings:
  Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
See ‘/home/travis/build/jeremyrcoyle/sl3/sl3.Rcheck/00install.out’ for details.checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘Untitled.R’
```
...the last part of which we can fix easily. (Not sure what `rgl` has to do with your PR.) I'll continue looking into this and report back if I find anything.

**Comment by imalenica** [comment]
It seems this is common issue with rgl and Travis: http://maxturgeon.ca/check-warnings
That should be fixed now. But 3.2.5 (oldrel) fails:

```
checking tests ... ERROR

  Running ‘testthat.R’ [469s/327s]

Running the tests in ‘tests/testthat.R’ failed.

Last 13 lines of output:

         method = "GET", ...)

  22: stopifnot(is(conn, "H2OConnection"))

  23: is(conn, "H2OConnection")

  24: h2o.getConnection()

  25: stop("No active connection to an H2O cluster. Did you run `h2o.init()` ?")

  

  Error in signalCondition(e) : 

    no function to return from, jumping to top level

  Calls: <Anonymous> ... .h2o.doREST -> stopifnot -> is -> h2o.getConnection

  testthat results ================================================================

  OK: 164 SKIPPED: 0 FAILED: 1

  1. Error: Super Learner for densities works (@test_zzz4_densitySL.R#22) 

  

  Error: testthat unit tests failed

  Execution haltedchecking top-level files ... NOTE

Non-standard file/directory found at top level:

  ‘Untitled.R’
```

**Comment by jeremyrcoyle** [comment]
Thanks for following up on this. I'm going to go ahead and merge this PR because I don't think it's what's causing the test to fail, then we can look into the test separately.

**Pull request merged**
