### PR TITLE
Lrnr Formula bug fix

### PR DESCRIPTION
**Pull request by Larsvanderlaan**
It previously added new_cols as the only covariates for the new task. So if the formula was "~.", an empty task was returned.

Also, it seems that `terms(form)` requires a data object if "." appears in the formula, which also led to an error.

(I didn't realize sl3 had this formula feature. This is great.)

### CODE REVIEW

**Comment by Larsvanderlaan** [comment]
The latest commit leads to a failed h20 cluster test. This change seems necessary. Do h20 tasks behave weird or something?

**Comment by Larsvanderlaan** [comment]
Hi @rachaelvp , would you mind reviewing these changes? Also, do you have any idea why the latest commit leads to a h20 error? There is no rush with any of this. Thank you for your help. Best, Lars

**Comment by Larsvanderlaan** [comment]
Are these changes no longer needed with #351?

**Comment by rachaelvp** [comment]
@Larsvanderlaan parts of this PR might still be needed. Could you please merge with the current version of devel first, and fix the conflicts, to check what is/isn't fixed in devel? For instance, even with the recent fix to formula, an empty task might still be returned if the formula is "~.". 

Also, I do not think I added a data object to `terms(form)` to cover the situation when "." appears in the formula. However, I think the formula "~." is just main terms, right? If so, that formula would invoke the default behavior. I am not sure why a user would specify that formula as it's not going to change anything, but still good to make sure it works.

Thank you very much for finding these errors ++ submitting PRs to fix them!

**Comment by rachaelvp** [comment]
Addressed in https://github.com/tlverse/sl3/pull/387

**Pull request closed without merging**
